---
---
kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  selector:
      app: node-exporter
  type: NodePort
  ports:
  - name: node-exporter
    protocol: TCP
    port: 9100
    targetPort: 9100
    nodePort: 30000
